name: Relase on pocketbase/release
on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest pocketbase version
        id: pocketbase
        uses: muchobien/repo-releases@main
        with:
          repository: pocketbase/pocketbase
          excludes: draft,prerelease
      
      - name: Get latest package version
        id: package
        run: |
          echo "::set-output name=version::$(curl -H "Authorization: token $GITHUB_TOKEN" -s https://api.github.com/orgs/muchobien/packages/container/pocketbase/versions | jq -r '.[0].metadata.container.tags[0]')"

      - name: Cancel if there is no changes
        if: ${{ steps.pocketbase.outputs.version == steps.package.outputs.version }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Version already released')

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: VERSION=${{ steps.pocketbase.outputs.version }}
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/muchobien/pocketbase:latest,ghcr.io/muchobien/pocketbase:${{ steps.pocketbase.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max